### PR TITLE
allow to get ESYS_CONTEXT from Context

### LINKED ISSUE #50: Allow Context to be unwrapped to ESYS_CONTEXT
Usage of the `Context` structure is fairly limited by the number of methods implemented on it. This restriction could be lifted if the `Context` could be unwrapped to expose the `ESYS_CONTEXT` beneath. 

This should be a one-way call, as once this is done, we can no longer keep track of generated handles. 

My suggestion would be to bundle up the Esys and TCTI contexts together with the handle set in a "shell" structure that is only used to access them. This would be incorporated in the `Context` to let it work as usual. Additionally, closing the contexts could be delegated to a custom implementation of `Drop` for the new structure.

### PR DESCRIPTION
**Pull request by genofire**
shout be fixed #50

### CODE REVIEW

**Comment by ionut-arm** [comment]
I was thinking of doing this, but then the Drop method would end up not properly cleaning up the handles being created.

Maybe we should add a method to add new handles to the set stored by the `Context`?

**Comment by ionut-arm** [comment]
I think we'll hold off with this for now, the main reason being that I'd want to avoid leaking the internal state of the `Context`. Extracting the inner context would be safer and easier to reason about (within the context). 

If you want, you can modify this PR to change the internal structure of the `Context` as described in #50 , but that will be a fairly large change!

**Comment by genofire** [comment]
I am not sure, maybe we use another function to create a safe context? If you do not like. Do not feel harm if you close this PR.

**Comment by hug-dev** [comment]
What is the status of this? I think our general view is that we want to "leak" or use as little as `bindgen` structures as possible and create abstractions for those. If there were any TSS operations needing the raw `ESYS_CONTEXT` that you wanted to use, do not hesitate making PRs for those, or raising them as issues 😃

**Comment by genofire** [comment]
so i close this PR now?

**Comment by hug-dev** [comment]
I think so, if you don't mind!

**Pull request closed without merging**
