### PR TITLE
Bump bindgen and update bindings

### PR DESCRIPTION
**Pull request by gowthamsk-arm**
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

### CODE REVIEW

**Review by Superhepper — APPROVED** [review]

**Review by Superhepper — COMMENTED** [review]
Have these really been generated from the 2.3.3 version of the tpm2-tss or are we thinking of updating the minimum supported TSS version to something higher?

**Comment by gowthamsk-arm** [comment]
The discussions on https://github.com/parallaxsecond/rust-tss-esapi/pull/439 is useful for this PR as well.

**Comment by tgonzalezorlandoarm** [comment]
I think this one depends on #448 for the CI to pass

**Review by tgonzalezorlandoarm — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
