### PR TITLE
Fix clippy errors

### PR DESCRIPTION
**Pull request by puiterwijk**
This fixes the Clippy errors that map_err is more succint than or_else
Err

Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

### CODE REVIEW

**Comment by puiterwijk** [comment]
@ionut-arm It was a relatively simple change to make :)

**Comment by puiterwijk** [comment]
Seems I missed one in `context.rs`. This should fix that.

**Comment by puiterwijk** [comment]
And next one (also fixed): clippy doesn't like useless type conversions (I guess this is a newer clippy than my version, because mine is totally fine with the code. So it may be a few more iterations).

**Comment by ionut-arm** [comment]
Indeed, with every iteration of the compiler some lints are added/removed to clippy (usually) and sometimes it breaks things :) We were talking about whether we should make compiler version updates manually to prevent these kind of build failures

**Pull request merged**
