### PR TITLE
Prepare patch release to fix docs.rs build

### PR DESCRIPTION
**Pull request by hug-dev**

### CODE REVIEW

**Review by Superhepper — APPROVED** [review]

**Review by ionut-arm — APPROVED** [review]

**Comment by ionut-arm** [comment]
The changes worked for cross-compilation at least, hopefully docs.rs is sorted too.

**Comment by hug-dev** [comment]
It worked 🥳 
https://docs.rs/tss-esapi-sys/0.1.1/tss_esapi_sys/

**Comment by ionut-arm** [comment]
Actually - I'm a bit worried/curious. That's the binding for `x86-unknown-linux-gnu` but there's clearly a difference between that and what a user running on Aarch64 Linux would see. Isn't that common for FFI crates in docs.rs? I don't remember if there was anything about it in that blogpost about doing FFI in Rust.

**Comment by hug-dev** [comment]
On docs.rs you can use the "Platform" option at the top to change what platform the docs have been generated for. We can customize that for the targets we want. [It's very easy](https://github.com/rust-embedded/cortex-m/commit/51dfa4d25f54705b2a7efb7fca08062b00bb1891)

**Comment by ionut-arm** [comment]
Oh wow, that's quite nice! Maybe we should do that for our crates

**Pull request merged**
