### PR TITLE
Add missing key handle session checks

### PR DESCRIPTION
**Pull request by Superhepper**
- Added checks for a key handle session to the context
  methods that according to the specification requires
  it.

Signed-off-by: Jesper Brynolf <jesper.brynolf@gmail.com>

### CODE REVIEW

**Review by ionut-arm — APPROVED** [review]
Hmmm, I thought there are other methods that would need a change like this, but I'll try and hunt them down in a different PR

**Comment by Superhepper** [comment]
There might be. This is for the ones I found in the esapi specification that explicitly mentioned '''keyHandkeSession'''

**Comment by ionut-arm** [comment]
> This is a breaking change.

Tbh I'd rather see this as a bug fix, even if it changes the "operation" of those methods.

**Comment by Superhepper** [comment]
Yeah, actually if you do not provide a session the error will come from the ESYS layer. We have just moved the error forward to the rust wrapper instead. So I am not sure I would define it as breaking if not some one uses the wrapper in a rather strange way.

**Pull request merged**
