### PR TITLE
Fixest lint errors for the 7.x.y branch.

### PR DESCRIPTION
**Pull request by Superhepper**
This commit addresses most of the problems
reported by the Clippy lint tool when building
with rust version 1.80 for the code in the 7.x.y
branch.

### CODE REVIEW

**Review by wiktor-k — DISMISSED** [review]
Looks straightforward, thanks!

Btw, as for `std::mem::size_of` in cryptoki it was apparently solved with an import: https://github.com/parallaxsecond/rust-cryptoki/pull/222/files

**Comment by wiktor-k** [comment]
I just checked and it seems it doesn't:

```
cryptoki$ git grep mem::siz
src/mechanism/mod.rs:17:use std::mem::size_of;
src/object.rs:14:use std::mem::size_of;
cryptoki$ cargo clippy
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
cryptoki$ cargo build
   Compiling cryptoki-sys v0.1.8 (/home/wiktor/src/open-source/cryptoki/cryptoki-sys)
   Compiling cfg-if v1.0.0
   Compiling zeroize v1.7.0
   Compiling log v0.4.20
   Compiling bitflags v1.3.2
   Compiling libloading v0.7.4
   Compiling secrecy v0.8.0
   Compiling cryptoki v0.7.0 (/home/wiktor/src/open-source/cryptoki/cryptoki)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.93s
cryptoki$ git grep unused
src/lib.rs:38:       unused,
src/lib.rs:39:       unused_allocation,
src/lib.rs:40:       unused_comparisons,
src/lib.rs:41:       unused_parens,
src/lib.rs:49:       unused_extern_crates,
src/lib.rs:50:       unused_import_braces,
src/lib.rs:51:       unused_qualifications,  // <---- it's here
src/lib.rs:52:       unused_results)]
rust-tss-esapi$ git grep unused_qua
tss-esapi/src/lib.rs:27:    unused_qualifications, // <--- looks like the same lint
tss-esapi/src/structures/buffers.rs:365:            #[allow(unused_qualifications)]
tss-esapi/src/structures/buffers.rs:369:            #[allow(unused_qualifications)]
tss-esapi/src/structures/buffers.rs:396:    #[allow(unused_qualifications)]
tss-esapi/src/structures/buffers/public.rs:27:    #[allow(unused_qualifications)]
tss-esapi/src/structures/buffers/sensitive.rs:26:    #[allow(unused_qualifications)]
tss-esapi/src/structures/buffers/sensitive_create.rs:26:    #[allow(unused_qualifications)]
tss-esapi/src/structures/ecc/point.rs:52:        #[allow(unused_qualifications)]
tss-esapi/src/structures/nv/storage/public.rs:30:    #[allow(unused_qualifications)]
$ cargo version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```

Maybe I'm holding it wrong. I wonder what do you see on your computer :thinking: 

Thanks for re-checking!

**Comment by Superhepper** [comment]
> I just checked and it seems it doesn't:
> 
> ```
> cryptoki$ git grep mem::siz
> src/mechanism/mod.rs:17:use std::mem::size_of;
> src/object.rs:14:use std::mem::size_of;
> cryptoki$ cargo clippy
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
> cryptoki$ cargo build
>    Compiling cryptoki-sys v0.1.8 (/home/wiktor/src/open-source/cryptoki/cryptoki-sys)
>    Compiling cfg-if v1.0.0
>    Compiling zeroize v1.7.0
>    Compiling log v0.4.20
>    Compiling bitflags v1.3.2
>    Compiling libloading v0.7.4
>    Compiling secrecy v0.8.0
>    Compiling cryptoki v0.7.0 (/home/wiktor/src/open-source/cryptoki/cryptoki)
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.93s
> cryptoki$ git grep unused
> src/lib.rs:38:       unused,
> src/lib.rs:39:       unused_allocation,
> src/lib.rs:40:       unused_comparisons,
> src/lib.rs:41:       unused_parens,
> src/lib.rs:49:       unused_extern_crates,
> src/lib.rs:50:       unused_import_braces,
> src/lib.rs:51:       unused_qualifications,  // <---- it's here
> src/lib.rs:52:       unused_results)]
> rust-tss-esapi$ git grep unused_qua
> tss-esapi/src/lib.rs:27:    unused_qualifications, // <--- looks like the same lint
> tss-esapi/src/structures/buffers.rs:365:            #[allow(unused_qualifications)]
> tss-esapi/src/structures/buffers.rs:369:            #[allow(unused_qualifications)]
> tss-esapi/src/structures/buffers.rs:396:    #[allow(unused_qualifications)]
> tss-esapi/src/structures/buffers/public.rs:27:    #[allow(unused_qualifications)]
> tss-esapi/src/structures/buffers/sensitive.rs:26:    #[allow(unused_qualifications)]
> tss-esapi/src/structures/buffers/sensitive_create.rs:26:    #[allow(unused_qualifications)]
> tss-esapi/src/structures/ecc/point.rs:52:        #[allow(unused_qualifications)]
> tss-esapi/src/structures/nv/storage/public.rs:30:    #[allow(unused_qualifications)]
> $ cargo version
> cargo 1.81.0 (2dbb1af80 2024-08-20)
> ```
> 
> Maybe I'm holding it wrong. I wonder what do you see on your computer 🤔
> 
> Thanks for re-checking!

You were absolutely right so I changed it. I will do the same thing for the main branch when I got the other stuff merged.

**Comment by wiktor-k** [comment]
Thanks!

**Review by ionut-arm — APPROVED** [review]
LGTM! 💯

**Pull request merged**
