### PR TITLE
Fixes CI problems with fedora rawhide.

### PR DESCRIPTION
**Pull request by Superhepper**

### CODE REVIEW

**Comment by Superhepper** [comment]
This needs to be combined with #489 in a single commit in order to work.

**Comment by wiktor-k** [comment]
> This needs to be combined with #489 in a single commit in order to work.

Hmm... is there a reason why this commit was not added to #489 directly? I see it has "Maintainers are allowed to edit this pull request." turned on.

**Comment by tgonzalezorlandoarm** [comment]
I've just brought that commit over to the mentioned PR, everything is passing now - Thanks!

**Comment by wiktor-k** [comment]
> I've just brought that commit over to the mentioned PR, everything is passing now - Thanks!

Do I get it right that we can close this PR now? (if so please press the button :bow: )

**Comment by Superhepper** [comment]
I made one to test it in isolation to try and see if I missed something else then i forgot to add it to the other PR.

**Pull request closed without merging**
