### PR TITLE
Update bindgen

### PR DESCRIPTION
**Pull request by ionut-arm**
cc @aplanas

### CODE REVIEW

**Comment by Superhepper** [comment]
Should you update the dependency in tss-esapi Cargo.toml as well?

**Comment by Superhepper** [comment]
What version of tpm2-tss did you use to regenerate these files?

**Comment by ionut-arm** [comment]
> What version of tpm2-tss did you use to regenerate these files?

2.40, I think - how much does it matter? Should I use something like 3.0.0 instead?

> Should you update the bindgen dependency in tss-esapi Cargo.toml as well?

The what?

**Comment by ionut-arm** [comment]
Oh, wait, no, I used the version from the string in the script - `3.2.1`. I think? I'll need to check.

**Comment by Superhepper** [comment]
Forget what I said about bindgen in tss-esapi I must have been dreaming. I thought we had a feature or build dependency in there as well.

Previously you have generated the bindings from the lowest version of tpm2-tss that we support.

**Review by aplanas — APPROVED** [review]

**Comment by ionut-arm** [comment]
Ok, all set now.

**Review by Superhepper — APPROVED** [review]

**Review by wiktor-k — APPROVED** [review]
Looks good 👍 sorry for the delay... was traveling 😅

**Pull request merged**
