### PR TITLE
Added integration test for pcr_extend

### PR DESCRIPTION
**Pull request by mkulke**
I didn't find a test for extending PCRs in the repo, it would be useful also as a reference

### CODE REVIEW

**Comment by Superhepper** [comment]
Well this is nice. But I think this is in the wrong place. ```pcr_extend``` is an actual Esys API so it should be a context method. 

So I think a better place for this test would be [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/tests/integration_tests/context_tests/tpm_commands/integrity_collection_pcr_tests.rs).

**Comment by mkulke** [comment]
> Well this is nice. But I think this is in the wrong place. `pcr_extend` is an actual Esys API so it should be a context method.
> 
> So I think a better place for this test would be [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/tests/integration_tests/context_tests/tpm_commands/integrity_collection_pcr_tests.rs).
> 
> Or maybe att it as an example in the documentation for that method if it is not properly documented.

Ah indeed, thx for clarifying. the linked test seems to cover pcr_extend. from glancing over it, I assumed it was testing some advanced tpm ceremony, but it's more or less the same test. I'll change this into an example similar to the hmac one and then you can decide whether it's a helpful addition.

**Comment by Superhepper** [comment]
Is this still in active development or should this be closed?

**Comment by Superhepper** [comment]
Closed due to non activity.

**Pull request closed without merging**
