### PR TITLE
Allow use with v4 of tpm2-tss

### PR DESCRIPTION
**Pull request by ionut-arm**
Also adding a test job for Fedora rawhide, which uses tpm2-tss v4.0.0 (for now).

@ansasaki - does this seem reasonable?

### CODE REVIEW

**Review by wiktor-k — APPROVED** [review]
I'd say this looks very clean and minimal. A couple of ignored test cases to be investigated but gosh, I wish that all major version bumps were this easy to handle!

Good job @ionut-arm :+1:

**Comment by ionut-arm** [comment]
> I'd say this looks very clean and minimal. A couple of ignored test cases to be investigated but gosh, I wish that all major version bumps were this easy to handle!

I don't think they need to be investigated, actually! See the latest comments on https://github.com/parallaxsecond/rust-tss-esapi/issues/383 - we'll just need to re-enable once the upstream problem goes away.

And yes, so far so good in terms of supporting v4 of tpm2-tss, it's mostly a testament to the work those folks have been doing to keep backwards compatibility for the ESAPI layer :)

**Comment by ansasaki** [comment]
@ionut-arm Yes, this looks good, thank you for the prompt action!

**Comment by wiktor-k** [comment]
> I don't think they need to be investigated, actually! See the latest comments on https://github.com/parallaxsecond/rust-tss-esapi/issues/383 - we'll just need to re-enable once the upstream problem goes away.

That's cool! I wonder if we need a FIXME comment in the source code or at least an action item on #383 to un-ignore these with later versions? Not sure about your memory but mine is excellent but very short :)

**Comment by Superhepper** [comment]
I have just looked through it briefly but from what I have seen it looks pretty good.

**Review by Superhepper — APPROVED** [review]

**Comment by Superhepper** [comment]
@ionut-arm 
We need to think carefully about if changing minimum rust version in that branch is a breaking change.

**Comment by ionut-arm** [comment]
> @ionut-arm We need to think carefully about if changing minimum rust version in that branch is a breaking change.

Yeah, I know. I guess if you have an application, not a library, you can control those dependencies underneath `tss-esapi` and keep using 1.53. But for libraries that doesn't work, right? They'd have to do the same as us.

**Comment by Superhepper** [comment]
Patch versions get updated like automatically but if we introduce it in a new minor version it would be possible lock your version of the library...

**Comment by ionut-arm** [comment]
Oh, I just realised that we're not actually making any changes that break our crate, we're just saying we don't/can't support 1.53 anymore because of changes upstream of us. I think that's perfectly fine - we can't really control any of that. Regardless of whether we change the MSRV, people will hit that problem.

> Patch versions get updated like automatically but if we introduce it in a new minor version it would be possible lock your version of the library...

Not really, AFAIK after v1.0.0 the minor numbers behave the same way - you can force Cargo to use a specific version, but by default it will use the latest with an equal major number.

Ok, I think I feel better about this now - I will bump the minor and do a release ASAP, after I get an ACK that this sounds reasonable to you as well, @wiktor-k @Superhepper.

**Comment by Superhepper** [comment]
Yeah sounds good

**Comment by Superhepper** [comment]
Can we merge this to master as well so that I do not need to redo all the fixes for the build.

**Comment by wiktor-k** [comment]
Yep, looks sensible and I agree with your reasoning @ionut-arm! :+1: 

Thanks!

**Pull request merged**
