### PR TITLE
Update MSRV 1.66.0

### PR DESCRIPTION
**Pull request by tgonzalezorlandoarm**
Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>

### CODE REVIEW

**Review by Superhepper — APPROVED** [review]
Thanks for the PR.

**Review by gowthamsk-arm — APPROVED** [review]
LGTM.

**Comment by wiktor-k** [comment]
Hi, it seems the codespell found some issues, I think they are relatively minor and could just be fixed in a follow-up commit. With one exception: it seems `AcSend` should be spelled like that and maybe it should be added here: https://github.com/parallaxsecond/rust-tss-esapi/blob/main/.codespellrc#L3 (as an exception)

**Comment by tgonzalezorlandoarm** [comment]
Hi @wiktor-k ! Yes, thanks for noticing. I have opened PR https://github.com/parallaxsecond/rust-tss-esapi/pull/448 for this, it has one approval already, could I get you to review that one as well ?

**Pull request merged**
