### PR TITLE
Add code coverage reporting

### PR DESCRIPTION
**Pull request by ionut-arm**
This commit adds a script and a nightly run for generating code coverage
reports for the `tss-esapi` crate.

Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>

### CODE REVIEW

**Review by Superhepper — APPROVED** [review]
Yes, this is an excellent idea

**Review by hug-dev — APPROVED** [review]
Thanks 👌

**Comment by hug-dev** [comment]
I triggered the workflow event but I am not sure what are the next steps to see it in https://codecov.io/gh/parallaxsecond
I'll let @ionut-arm do what's needed ☔

**Comment by ionut-arm** [comment]
Coverage results are now available at https://app.codecov.io/gh/parallaxsecond/rust-tss-esapi

The nightly run won't be able to update it, likely because [we're running it in Docker](https://docs.codecov.io/docs/testing-with-docker)

**Pull request merged**
