### PR TITLE
Bump version for new alpha release

### PR DESCRIPTION
**Pull request by ionut-arm**
Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>

### CODE REVIEW

**Review by Superhepper — APPROVED** [review]

**Review by anta5010 — APPROVED** [review]

**Comment by hug-dev** [comment]
Sorry coming on this late. Linking with https://github.com/parallaxsecond/parsec/issues/527, is there any reason why we upstreamed a new `alpha` version? Is the expectation that we are going to upstream a `7.0.0` soon once the `alpha` release is seemed to work normally?

**Comment by Superhepper** [comment]
Yeah the alpha versions are not pushed to crates.io I think.

**Comment by anta5010** [comment]
> Yeah the alpha versions are not pushed to crates.io I think.

It's there https://crates.io/crates/tss-esapi/7.0.0-alpha.1 and I can build parsec 0.8.1 from crates

**Comment by Superhepper** [comment]
Oh well then I guess the reason is to see if there are any serious flaws in the release that would require an API breaking change to be fixed. Yet it is still needed in order to fix other things. So in order to get something out that can be tested then an alpha is released.

**Comment by Superhepper** [comment]
And another thing. In order for Parsec 0.8.1 to be published to crates.io I think its dependencies needs to published there as well.

**Comment by hug-dev** [comment]
Found Ionut's [message](https://cloud-native.slack.com/archives/C01EARH2ZB3/p1631093937027500?thread_ts=1631091195.026100&cid=C01EARH2ZB3) on Slack explaining that the next release was going to be an `alpha` (because a lot of things changed in the API so we need some time before making a new release).

**Pull request merged**
